Typography Task-1/Vishesh-Vijay.txt

Issue: 1
####
- Differentiation of heading and subheadings
-colour schema given to headings and subheadings
-emojis added
-white spaces between two different content
-bulleting listed points

Typography Task1 completed

---

Typography Task-1/iamatifmoin.txt

Issue: 2
I have added the link to my typography document.

typography task done (issue 2)

---

Typography Task-1/SanyamAgrawal07.txt

Typography task1 by SanyamAgrawal07

---

Typography Task-1/RayLikesAnime.txt

Issue: 2
styling and heirarchy
ok

Typography Text 1

---

Typography Task-1/ananyaa07.txt

Issue: 2
I have completed Typography - task 1

Completed-Task1

---

Typography Task-1/Typography Task1.txt

Issue: 2
- typography txt file created

Create Typography Task1.txt

---

Play with shapes-1/aasthaaaa7.txt
Typography Task-1/aasthaaaa7.txt

let's design task 2

---

Typography Task-1/aasthaaaa7.txt

typography task

---

Play with shapes-1/ananyaa07.txt

Issue: 11
I have tried to replicate the figure given using figma.

Task-completed

---

Typography Task-1/anshgeez31.txt

Task 1 Done

---

Typography Task-1/sushantk1274.txt

Issue: 2
added google doc link in text file

task1 done

---

Typography Task-1/jaydeepxx.txt

typography task done

---

Typography Task-1/antsharma.txt

Issue: 2
This contains a link to a google docs file completed with the required task of building typography.

Typography-task1-done

---

Typography Task-1/typography.txt

completed typography

---

Typography Task-1/zitsav.txt

Issue: 2
Added a link to the document for the typography task.
Added a link to the document for the typography task.
-
-
-

Typography Task 1 Completed

---

Typography Task-1/thedivineaurora.txt

Issue: 2
2
Added typhography
added thedivineaurora.txt 
-
-
-

issue_2_typhography

---

Play with shapes-1/SanyamAgrawal07.txt

Shapes task done by SanyamAgrawal07

---

Typography Task-2/thedivineaurora.txt

Issue: 38
38
TyphoGraphy task -2
added a "design" edit figma url into the thedivineaurora.txt
-
-
-

issue_38_Typhography_task_2

---

Play with shapes-1/Siddhant-Agarwal4583.ai

Issue: 11
Completed Play with shapes-1
-
-
-

Added Siddhant-Agarwal4583.ai to Play with shapes-1

---

Play with shapes-1/hargunkaur286.txt

Issue: 11
Completed play with shapes-1
Here is a screenshot of play with shapes-1 figma file.

Play with shapes

---

Pen tool Task-1/radhikag970.txt

Issue: 49
Pen Tool Task Done. The Screenshot is attached.

Pen Tool Task Done

---

Pen tool Task-1/Siddhant-Agarwal4583.ai

Issue: 49
Completed Pen tool Task-1
-
-
-

Pen tool Task-1 completed by Siddhant-Agarwal4583

---

Pen tool Task-1/thedivineaurora.txt

Issue: 49
49
vectors in figma
added txt file 
-
-
-

#49_Pen tool task - 1

---

Pen tool Task-1/SanyamAgrawal07.txt

Pen tool task done by SanyamAgrawal07

---

Pen tool Task-1/ananyaa07.txt

pen-task-done

---

Pen tool Task-1/aasthaaaa7.txt

pen task 1

---

Pen tool Task-1/pen tool   -task 1.txt

Completed task-1

---

Play with shapes-1/shapes_BINGABABA.txt

hola again

---

Pen tool Task-1/RibhavBansal.txt
Typography Task-2/RibhavBansal.txt

Issue: 38
- TyphoGraphy task -2
- add a Typography Task-2 folder

Typography task-2

---

Typography Task-2/anshgeez31.txt

Typography-2 Done

---

Avatar Design/SanyamAgrawal07.txt

Avatar task completed

---

Pen tool Task-2/Figma Link akshayw1.txt

Issue: 82
82
Added Figma Link for task 2
-
-
-

Added Figma Link for task 2

---

Pen tool Task-2/SanyamAgrawal07.txt

Pen Tool Task 2 done

---

Merry Christmas/ananyaa07.txt

christmas-poster

---

Avatar Design/ananyaa07.txt

avatars-completed

---

Pen tool Task-2/ananyaa07.txt

pen-task-2

---

Merry Christmas/anshgeez31.txt

Merry Christmas

---

Avatar Design/thedivineaurora.txt

Issue: 77
77
avatar designs figma link
-
-
-

avatar design issue _ 77

---

Merry Christmas/hargunkaur286.txt

Issue: 78
added poster for christmas

added christmas poster

---

Merry Christmas/SanyamAgrawal07.txt

Merry Christmas :)

---

Pen tool Task-2/TheDivineAurora.txt

Issue: 82
82
bonus , which i couldnt submit
-
-
-

squirell pen tool task -2

---

Avatar Design/hargunkaur286.txt

Issue: 77
added avatar designs

added avatar designs

---

Merry Christmas/aasthaaaa7.txt
Pen tool Task-2/aasthaaaa7.txt

pen tool task 2

---

Pen tool Task-2/radhikag970.txt

Issue: 82
Pen Tool Task-2 Done.
-
-
-

Pen Tool Task-2 Done

---

LOGO Design/Vishesh-VIjay.txt

logo design task completed

---

LOGO Design/theDivineAurora.txt

 logo design figma link

---

Avatar Design/anshgeez31.txt

Avtaar Done

---

LOGO Design/anshgeez31.txt

Logo designed

---

Avatar Design/radhikag970.txt

Issue: 77
Avatar Design Task done
-
-
-

Avatar Design

---

LOGO Design/bhumika-kalaru.txt

Issue: 120
- Designed a Logo for code plus

LOGO Design

---

Business Card Design/anshgeez31.txt

Business Card

---

Business Card Design/ananyaa07.txt

business-card

---

Business Card Design/Koshal7.txt

Business Card Task

---

Business Card Design/JahnaviGadde.txt

Issue: 148
Created a Business card 
Created a Business card 
-
-
-

Business Card - JahnaviGadde

---

Business Card Design/bhumika-kalaru.txt

Issue: 148
- Business Card Design

Business Card Design

---

Happy New Year 2023/bhumika-kalaru.txt

Issue: 155
- Created New Year poster

Happy New Year

---

Happy New Year 2023/Vishesh-Vijay.txt
Vector Design-1/Vishesh-Vijay.txt

Happy New Year task done

---

Happy New Year 2023/aasthaaaa7.txt

Issue: 155
happy new year poster

new year poster

---

Vector Design-1/aasthaaaa7.txt

kite vector

---

Vector Design-1/radhikag970.txt

Issue: 156
Kite Festival Poster Done
-
-
-

Poster Done

---

Vector Design-1/ananyaa07.txt

vector-kite

---

Happy New Year 2023/shashi.txt
Happy New Year 2023/shashiii.txt
Vector Design-1/shashii.txt

Made the Vector Design 

---

Happy New Year 2023/shashi.txt
Happy New Year 2023/shashiii.txt

Happy new year design

---

Vector Design-1/SanyamAgrawal07.txt

Vector Design task 1

---

Doodle Design/thedivineaurora.txt

Issue: 179
179
figma link
-
-
-

doodle design

---

TriFold Brochure Design/aasthaaaa7.txt

Issue: 180
trifold travel brochure

travel brochure

---

TriFold Brochure Design/anshgeez31.txt

Tri-Fold Brochure

---

Drop Down Task/SanyamAgrawal07.txt

Dropdown menu

---

Cartoon Vector Design/bhumika-kalaru.ai

Cartooooon

---

Cartoon Vector Design/Koshal7.txt

Cartoon Vector

---

Drop Down Task/Koshal7.txt

Drop Down Menu

---

Cartoon Vector Design/SanyamAgrawal07.txt

Cartoon vector design

---

Drop Down Task/aasthaaaa7.txt

drop down task

---

Glass Effect Task/JackofAllCodez.txt
Toggle Button Task/JackofAllCodez.txt

Toggle Button Done

---

Glass Effect Task/Koshal7.txt

Glass Effect Task

---

Toggle Button Task/Rohit_110.txt
Toggle Button Task/Toggle Button Task

Toggle Task Done 

---

Glass Effect Task/Rohit_110.txt

Rohit-110.txt

---

Toggle Button Task/Koshal7.txt

Toggle Button Task

---

Toggle Button Task/aasthaaaa7.txt

toggle button

---

Horizontal Scroll/aasthaaaa7.txt
Vertical Scroll/aasthaaaa7.txt

horizontal scroll

---

Glass Effect Task/ananyaa07.txt

glass effect

---

Vertical Scroll/SanyamAgrawal07.txt

Vertical Scroll Task

---

Horizontal Scroll/bhumika-kalaru.txt

Vertical Scroll

---

Hamburger Menu Task/JackofAllCodez.txt

Hamburger Menu Done

---

ToolTip Task/SanyamAgrawal07.txt

Tooltip task

---

Check Box Task/Koshal7.txt

Checkbox Task

---

Hamburger Menu Task/Koshal7.txt

Hamburger Menu Task

---

Hamburger Menu Task/SanyamAgrawal07.txt

Hamburger task

---

Check Box Task/Rohit-110.txt

Checkbox Task Done

---

ToolTip Task/Rohit-110.txt

ToolTip Task Done

---

Animated Loading Screen Task/Rohit-110.txt

Animated Loading Screen Task

---

Animated Loading Screen Task/ananyaa07.txt

animate screen
